class InsertUser < ActiveRecord::Migration
  def change
    c=User.find_or_create_by_id(1);c.update_attributes({ :name => '浅野友希', :email => 'yuuki@gmail.com', :password => 'yuuki1224', :image_name => 'asano.png', :occupation => 'エンジニア', :comad_id => 'yuuki1224', :description => '学生エンジニアです。好きな言語はPHPです。', :question1 => '立命館大学', :question2 => 'Ruby', :question3 => 'Photoshop', :question4 => '秀丸' }, without_protection: true)
    c=User.find_or_create_by_id(2);c.update_attributes({ :name => '足立壮大', :email => 'takehiro@gmail.com', :password => 'adachi1224', :image_name => 'adachi.png', :occupation => 'エンジニア', :comad_id => 'tkhr', :description => '学生エンジニアです。好きな言語はRubyです。', :question1 => '立命館大学', :question2 => 'Ruby', :question3 => 'Photoshop', :question4 => 'Vim'}, without_protection: true)
    c=User.find_or_create_by_id(3);c.update_attributes({ :name => '中川峰志', :email => 'nakagawa@gmail.com', :password => 'nakagawa1224', :image_name => 'nakagawa.png', :occupation => 'エンジニア', :comad_id => 'tak03', :description => '学生エンジニアです。好きな言語はJavaScriptです。', :question1 => 'Google社内のスペース', :question2 => 'Javascript', :question3 => 'Photoshop', :question4 => 'SublimeText2'}, without_protection: true)
    c=User.find_or_create_by_id(4);c.update_attributes({ :name => '吉田万輝', :email => 'yoshida@gmail.com', :password => 'yoshida1224', :image_name => 'yoshida.png', :occupation => 'エンジニア', :comad_id => 'kazy', :description => '学生エンジニアです。好きな言語はPhythonです。', :question1 => '同志社大学京田辺キャンパス図書館', :question2 => 'Phython', :question3 => 'Photoshop', :question4 => 'Vim for mac'}, without_protection: true)
    c=User.find_or_create_by_id(5);c.update_attributes({ :name => '佐藤大輔', :email => 'sato@gmail.com', :password => 'sato1224', :image_name => 'sato.png', :occupation => 'エンジニア', :comad_id => 'daisuke', :description => '学生エンジニアです。好きな言語はObjective-Cです。', :question1 => '立命館大学', :question2 => 'Objective-C', :question3 => 'Photoshop', :question4 => 'Vim'}, without_protection: true)
    c=User.find_or_create_by_id(6);c.update_attributes({ :name => '松本凌', :email => 'matsumoto@gmail.com', :password => 'matsumoto1224', :image_name => 'matsumoto.png', :occupation => 'エンジニア', :comad_id => 'busssorenre', :description => '学生エンジニアです。好きな言語はCです。', :question1 => '立命館大学びわこ草津キャンパス', :question2 => 'Ruby on Rails', :question3 => 'Photoshop', :question4 => 'SublimeText'}, without_protection: true)
    c=User.find_or_create_by_id(7);c.update_attributes({ :name => '村田温美', :email => 'murata@gmail.com', :password => 'murata1224', :image_name => 'murata.png', :occupation => 'エンジニア', :comad_id => 'mura_atsu', :description => 'Campusデザイナーです。好きな言語はCoffeescriptです。', :question1 => '寒梅館', :question2 => 'CoffeeScript', :question3 => 'Photoshop, Illustrator', :question4 => 'SublimeText'}, without_protection: true)
    c=User.find_or_create_by_id(8);c.update_attributes({ :name => '小林大志', :email => 'kobayashi@gmail.com', :password => 'kobayashi1224', :image_name => 'kobayashi.png', :occupation => 'エンジニア', :comad_id => 'taishi', :description => '学生エンジニアです。好きな言語はphpです。', :question1 => 'Campusオフィス', :question2 => 'Ruby', :question3 => 'Photoshop', :question4 => 'vim'}, without_protection: true)
    c=User.find_or_create_by_id(9);c.update_attributes({ :name => '林奈央', :email => 'hayashi@gmail.com', :password => 'hayashi1224', :image_name => 'hayashi.png', :occupation => 'デザイナー', :comad_id => 'naohys', :description => '元Campusデザイナーです。好きな言語はぴょんさんです。', :question1 => '兵庫県', :question2 => 'html', :question3 => 'Photoshop, Illustrator', :question4 => 'Vim'}, without_protection: true)
    c=User.find_or_create_by_id(10);c.update_attributes({ :name => '石丸翔也', :email => 'ishimaru@gmail.com', :password => 'ishimaru1224', :image_name => 'ishimaru.png', :occupation => 'エンジニア', :comad_id => 'mrk1869', :description => 'ドイツで人口知能を研究をしてます。', :question1 => 'ドイツ', :question2 => 'html', :question3 => 'Photoshop, Illustrator', :question4 => 'Vim'}, without_protection: true)
    c=User.find_or_create_by_id(11);c.update_attributes({ :name => '原美雪', :email => 'miyuki@gmail.com', :password => 'miyuki1224', :image_name => 'hara.png', :occupation => 'デザイナー', :comad_id => 'miyuk1', :description => 'Campusデザイナーです。好きな言語はhtml5です。', :question1 => '滋賀', :question2 => 'html', :question3 => 'Photoshop, Illustrator', :question4 => 'Vim'}, without_protection: true)
    c=User.find_or_create_by_id(12);c.update_attributes({ :name => '安武沙也加', :email => 'yasutake@gmail.com', :password => 'yasutake1224', :image_name => 'yasutake.png', :occupation => 'デザイナー', :comad_id => 'sachan', :description => '元Campusデザイナーです。好きなAdobe製品はPhotoshopです。', :question1 => '京都', :question2 => 'html', :question3 => 'Photoshop, Illustrator', :question4 => 'Vim'}, without_protection: true)
    c=User.find_or_create_by_id(13);c.update_attributes({ :name => '小澤佳佑', :email => 'ozawa@gmail.com', :password => 'ozawa1224', :image_name => 'ozawa.png', :occupation => 'プランナー', :comad_id => 'ozawa', :description => 'ボランディアサイトを運営してます。', :question1 => '立命館', :question2 => 'html', :question3 => 'Photoshop, Illustrator', :question4 => 'Vim'}, without_protection: true)
    c=User.find_or_create_by_id(14);c.update_attributes({ :name => '山本翔大', :email => 'yamamoto@gmail.com', :password => 'yamamoto1224', :image_name => 'yamamoto.png', :occupation => 'デザイナー', :comad_id => 'yamasho', :description => '元Campusデザイナーです。ダンスが得意です。', :question1 => '阪大', :question2 => 'html', :question3 => 'Photoshop, Illustrator', :question4 => 'Vim'}, without_protection: true)
    c=User.find_or_create_by_id(15);c.update_attributes({ :name => '國重侑輝', :email => 'kunishige@gmail.com', :password => 'kunishige1224', :image_name => 'kunishige.png', :occupation => 'Campus社長', :comad_id => 'kunikuni', :description => '株式会社Campusの社長です。', :question1 => 'Campus', :question2 => 'html', :question3 => 'Photoshop, Illustrator', :question4 => 'Vim'}, without_protection: true)
    c=User.find_or_create_by_id(16);c.update_attributes({ :name => '繁谷悠', :email => 'shigetani@gmail.com', :password => 'shigetani1224', :image_name => 'shigetani.png', :occupation => 'エンジニア', :comad_id => 'shigetani', :description => '元Campusエンジニアです。', :question1 => '立命館', :question2 => 'html', :question3 => 'Photoshop, Illustrator', :question4 => 'Vim'}, without_protection: true)
    c=User.find_or_create_by_id(17);c.update_attributes({ :name => '高松直也', :email => 'takamatsu@gmail.com', :password => 'takamatsu1224', :image_name => 'takamatsu.png', :occupation => 'エンジニア', :comad_id => 'nackuru', :description => 'ナックルです！Life is Tech!のメンターです！', :question1 => '兵庫県', :question2 => 'html', :question3 => 'Photoshop, Illustrator', :question4 => 'Vim'}, without_protection: true)
  end
end
