class InsertUser < ActiveRecord::Migration
  def change
    c=User.find_or_create_by_id(1);c.update_attributes({ :name => '浅野友希', :email => 'yuuki@gmail.com', :password => 'yuuki1224', :image_name => 'asano.png', :occupation => 'エンジニア', :comad_id => 'yuuki1224', :description => '学生エンジニアです。好きな言語はPHPです。' }, without_protection: true)
    c=User.find_or_create_by_id(2);c.update_attributes({ :name => '足立壮大', :email => 'takehiro@gmail.com', :password => 'adachi1224', :image_name => 'adachi.png', :occupation => 'エンジニア', :comad_id => 'tkhr', :description => '学生エンジニアです。好きな言語はRubyです。'}, without_protection: true)
    c=User.find_or_create_by_id(3);c.update_attributes({ :name => '中川峰志', :email => 'nakagawa@gmail.com', :password => 'nakagawa1224', :image_name => 'nakagawa.png', :occupation => 'エンジニア', :comad_id => 'tak03', :description => '学生エンジニアです。好きな言語はJavaScriptです。' }, without_protection: true)
    c=User.find_or_create_by_id(4);c.update_attributes({ :name => '吉田万輝', :email => 'yoshida@gmail.com', :password => 'yoshida1224', :image_name => 'yoshida.png', :occupation => 'エンジニア', :comad_id => 'kazy', :description => '学生エンジニアです。好きな言語はPhythonです。'}, without_protection: true)
    c=User.find_or_create_by_id(5);c.update_attributes({ :name => '佐藤大輔', :email => 'sato@gmail.com', :password => 'sato1224', :image_name => 'sato.png', :occupation => 'エンジニア', :comad_id => 'daisuke', :description => '学生エンジニアです。好きな言語はObjective-Cです。'}, without_protection: true)
    c=User.find_or_create_by_id(6);c.update_attributes({ :name => '松本凌', :email => 'matsumoto@gmail.com', :password => 'matsumoto1224', :image_name => 'matsumoto.png', :occupation => 'エンジニア', :comad_id => 'busssorenre', :description => '学生エンジニアです。好きな言語はCです。'}, without_protection: true)
    c=User.find_or_create_by_id(7);c.update_attributes({ :name => '村田温美', :email => 'murata@gmail.com', :password => 'murata1224', :image_name => 'murata.png', :occupation => 'エンジニア', :comad_id => 'mura_atsu', :description => '学生エンジニアです。好きな言語はSassです。'}, without_protection: true)
    c=User.find_or_create_by_id(8);c.update_attributes({ :name => '小林大志', :email => 'kobayashi@gmail.com', :password => 'kobayashi1224', :image_name => 'kobayashi.png', :occupation => 'エンジニア', :comad_id => 'taishi', :description => '学生エンジニアです。好きな言語はHTMLです。'}, without_protection: true)
    c=User.find_or_create_by_id(9);c.update_attributes({ :name => '林奈央', :email => 'hayashi@gmail.com', :password => 'hayashi1224', :image_name => 'hayashi.png', :occupation => 'デザイナー', :comad_id => 'naohys', :description => '元Campusデザイナーです。好きな言語はぴょんさんです。'}, without_protection: true)
  end
end
